server:
  port: 18080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://rm-bp1o4cee732db9nxblo.mysql.rds.aliyuncs.com:3306/iam
    username: iam
    password: iam_Wttch96
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit:

wttch:
  wcbs:
    init-sql-path:
    # - classpath:modify-sql/*.sql
  data:
    database:
      primary:
      connection:
        test:
          url:
          password:


